In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
#import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [3]:
(2**np.arange(1,21))/np.arange(1,21)

array([  2.00000000e+00,   2.00000000e+00,   2.66666667e+00,
         4.00000000e+00,   6.40000000e+00,   1.06666667e+01,
         1.82857143e+01,   3.20000000e+01,   5.68888889e+01,
         1.02400000e+02,   1.86181818e+02,   3.41333333e+02,
         6.30153846e+02,   1.17028571e+03,   2.18453333e+03,
         4.09600000e+03,   7.71011765e+03,   1.45635556e+04,
         2.75941053e+04,   5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [34]:
(0.1**(3*np.arange(6))*0.2**(4*np.arange(6))).sum()

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [7]:
ar = np.zeros((8,8))
ar[1::2, ::2] = 1
ar[::2, 1::2] = 1
ar

array([[ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [33]:
import math as m
X = np.random.random((5, 2))
r = np.sqrt(X[:,0]**2*X[:,1]**2).reshape(5,1)
fi = np.arctan(X[:,1]/X[:,0]).reshape(5,1)
X = np.hstack((r, f))
print(X)

[[ 0.40132122  0.37197749]
 [ 0.89369978  0.23539651]
 [ 0.70658571  0.75506994]
 [ 0.88796011  0.96341287]
 [ 0.56747279  0.95396312]]
[[ 0.14928246  0.94366282]
 [ 0.21037381  1.01438872]
 [ 0.53352164  0.78621489]
 [ 0.8554722   0.42943347]
 [ 0.54134811  0.52981572]]


**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [59]:
X = np.random.random((10, 10))
p = np.argmax(X)
r = p//10
c = p%10
max_elem = X[r,c]
print(p)
print(r)
print(c)
print(max_elem)

37
3
7
0.99536686792


**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [74]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
dist = (X[:,0]-y[0,0])**2 + (X[:,1]-y[0,1])**2
index = np.argmin(dist)
nearest_x = X[index]
min_dist = dist[index]
print(y[0])
print(nearest_x)
print(min_dist)

[ 0.87792135  0.48592332]
[ 0.87528636  0.63334726]
0.0217407619573


**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [96]:
def func(x):
    if x<0:
        return x**2+2*x+6
    elif x<=2:
        return x+6
    elif x>2:
        return x**2+4*x-4
        
vfunc = np.vectorize(func)
x = np.linspace(-3,3,13)
res = vfunc(x)
print(x)
print(res)

[-3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3. ]
[  9.     7.25   6.     5.25   5.     5.25   6.     6.5    7.     7.5    8.
  12.25  17.  ]


**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [67]:
X = np.random.random((10, 10))
mean = np.mean(X,axis=1).reshape(10,1)
X-=mean
print(np.mean(X,axis=1))

[  5.55111512e-17  -1.11022302e-17   0.00000000e+00  -2.22044605e-17
  -3.33066907e-17  -4.44089210e-17  -2.22044605e-17  -9.99200722e-17
   1.11022302e-17   0.00000000e+00]


**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [4]:
X = np.random.normal(loc=5, scale=2., size=1000)
sample_mean = np.mean(X)
dispersion = np.var(X)
print(sample_mean)
print(dispersion)

5.02597402728
4.01104613607


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [3]:
X = np.zeros((5,5))
X[range(5)] = range(5)
X = X+X.T
X = X%5
print(X)

[[ 0.  1.  2.  3.  4.]
 [ 1.  2.  3.  4.  0.]
 [ 2.  3.  4.  0.  1.]
 [ 3.  4.  0.  1.  2.]
 [ 4.  0.  1.  2.  3.]]
